# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-10 07:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='type',
            new_name='user_type',
        ),
    ]
